-------------------------------------------------------------------------------
-- VHDL Entity fpga_fmc230.fpga_fmc230_top_tb.symbol
-- Generated by Mentor Graphics' HDL Designer(TM) 2008.1b (Build 7)
-------------------------------------------------------------------------------
-- Source   : fpga_fmc230_top_tb/symbol.bd
-- Author   : steel_lake 
-- Company  : Rohde & Schwarz
-- Created  : 19:13:43 03/10/2014
-- Platform : PC
-- Filename : fpga_fmc230_top_tb_struct.vhd
-------------------------------------------------------------------------------
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;


entity fpga_fmc230_top_tb is
-- Declarations

end fpga_fmc230_top_tb ;
-------------------------------------------------------------------------------
-- VHDL Architecture fpga_fmc230.fpga_fmc230_top_tb.struct
-- Generated by Mentor Graphics' HDL Designer(TM) 2008.1b (Build 7)
-------------------------------------------------------------------------------
-- Source   : fpga_fmc230_top_tb/struct.bd
-- Author   : steel_lake 
-- Company  : Rohde & Schwarz
-- Created  : 19:13:43 03/10/2014
-- Platform : PC
-- Filename : fpga_fmc230_top_tb_struct.vhd
-------------------------------------------------------------------------------
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

library fpga_fmc230;

architecture struct of fpga_fmc230_top_tb is

   -- Architecture declarations

   -- Internal signal declarations
   signal clk_out  : std_logic;
   signal clk_tb   : std_logic;
   signal logic_0  : std_logic;
   signal logic_1  : std_logic;
   signal reset    : std_logic;
   signal reset_b  : std_logic;
   signal sim_done : boolean := false;


   -- Component Declarations
   component fpga_fmc230_top
   port (
      clk_in  : in     std_logic ;
      clk_out : out    std_logic 
   );
   end component;

   -- Optional embedded configurations
   -- synthesis synthesis_off
   for all : fpga_fmc230_top use entity fpga_fmc230.fpga_fmc230_top;
   -- synthesis synthesis_on


begin
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   clk_gen_clock : block
   
   constant c_CLK_PERIOD : time := 50 ns;
   signal clk : std_logic;
   
   begin
    
       clk_tb <= clk;
    
       p_clk : process
       begin
           while not(sim_done) loop
               wait for c_CLK_PERIOD / 2;
               clk <= '1';
               wait for c_CLK_PERIOD / 2;
               clk <= '0';
               end loop;
           wait;
       end process;
    
   end block;
   

   -- HDL Embedded Text Block 2 eb2
       p_reset : process
       begin
           reset   <= '1';
           reset_b <= '0';
           wait for 1 us;
           reset   <= '0';
           reset_b <= '1';
           wait;
       end process;


   -- ModuleWare code(v1.9) for instance 'U_1' of 'gnd'
   logic_0 <= '0';

   -- ModuleWare code(v1.9) for instance 'U_0' of 'vdd'
   logic_1 <= '1';

   -- Instance port mappings.
   u_fpga_fmc230_top : fpga_fmc230_top
      port map (
         clk_in  => clk_tb,
         clk_out => clk_out
      );

end struct;
