-------------------------------------------------------------------------------
-- VHDL Entity fpga_fmc230.fpga_fmc230_top.symbol
-- Generated by Mentor Graphics' HDL Designer(TM) 2008.1b (Build 7)
-------------------------------------------------------------------------------
-- Source   : fpga_fmc230_top/symbol.bd
-- Author   : steel_lake 
-- Company  : Rohde & Schwarz
-- Created  : 19:13:32 03/10/2014
-- Platform : PC
-- Filename : fpga_fmc230_top_struct.vhd
-------------------------------------------------------------------------------
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity fpga_fmc230_top is
   port( 
      clk_in  : in     std_logic;
      clk_out : out    std_logic
   );

-- Declarations

end fpga_fmc230_top ;
-------------------------------------------------------------------------------
-- VHDL Architecture fpga_fmc230.fpga_fmc230_top.struct
-- Generated by Mentor Graphics' HDL Designer(TM) 2008.1b (Build 7)
-------------------------------------------------------------------------------
-- Source   : fpga_fmc230_top/struct.bd
-- Author   : steel_lake 
-- Company  : Rohde & Schwarz
-- Created  : 19:13:32 03/10/2014
-- Platform : PC
-- Filename : fpga_fmc230_top_struct.vhd
-------------------------------------------------------------------------------
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;


architecture struct of fpga_fmc230_top is

   -- Architecture declarations

   -- Internal signal declarations



begin

   -- ModuleWare code(v1.9) for instance 'in_out' of 'assignment'
   clk_out <= clk_in;

   -- Instance port mappings.

end struct;
